Release 1.6
spinupwp/spinupwp-plugin pull request #76
Opened 2024-01-29 13:47 UTC by Jamesclark32

Includes:
 - #63 
 - #68 
 - #70 
 - #71 
 - #73 
 - #75

2024-01-29 15:44 UTC, bradt requested changes
I've suggested some changes to the changelog entries. Please also reorder them so that it's new first, followed by improvements, then bug fixes.

2024-01-29 15:44 UTC, bradt commented on readme.txt
> +* Add option to purge current URL.
```suggestion
* New: Add "Purge this URL" option to our Cache menu in the WordPress nav bar.
```

2024-01-29 15:44 UTC, bradt commented on readme.txt
> +* Increase default timeout limits from 1 to 5 seconds.
```suggestion
* Improvement: Increase default cache purge timeout limit from 1 to 5 seconds.
```

2024-01-29 15:44 UTC, bradt commented on readme.txt
> +* Fix "Deprecated: file_exists()" on PHP 8.1.
```suggestion
* Improvement: PHP 8.1 compatibility. /props afragen
```

2024-01-29 15:44 UTC, bradt commented on readme.txt
> +* Allow cache key customization.
```suggestion
* New: Cache key customization. /props quimcastella
```

2024-01-29 15:44 UTC, bradt commented on readme.txt
> +* Fix 'Clear All Cache' page cache functionality when Redis errors.
```suggestion
* Bug Fix: Page cache not cleared when clearing object cache fails.
```

2024-01-31 11:06 UTC, A5hleyRich commented on drop-ins/object-cache.php
> +			define( 'WP_REDIS_PREFIX', get_cache_key_salt());
```suggestion
        define( 'WP_REDIS_PREFIX', get_cache_key_salt());
```

2024-01-31 11:06 UTC, A5hleyRich commented on drop-ins/object-cache.php
> +			define( 'WP_REDIS_SELECTIVE_FLUSH', true );
```suggestion
        define( 'WP_REDIS_SELECTIVE_FLUSH', true );
```

2024-01-31 11:07 UTC, A5hleyRich commented on drop-ins/object-cache.php
> +	return null;
```suggestion
    if ( defined( 'SPINUPWP_CACHE_KEY_SALT' ) ) {
        return SPINUPWP_CACHE_KEY_SALT;
    }
    if ( getenv( 'SPINUPWP_CACHE_KEY_SALT' ) ) {
        return getenv( 'SPINUPWP_CACHE_KEY_SALT' );
    }
    if ( defined( 'WP_CACHE_KEY_SALT' ) ) {
        // @deprecated
        return WP_CACHE_KEY_SALT;
    }

    return null;
```

2024-01-31 11:28 UTC, A5hleyRich commented
Reviewed and tested. Just those few code formatting suggestions.

2024-01-31 15:56 UTC, merged